/**
 * BranchLocatorAPI
 * Branch API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: contact@hsbc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BranchLocatorResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-15T11:18:16.803Z")
public class BranchLocatorResponse   {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("Lat")
  private String lat = null;

  @SerializedName("Long")
  private String _long = null;

  public BranchLocatorResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of Branch
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of Branch")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BranchLocatorResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Branch Id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Branch Id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BranchLocatorResponse lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Latitude
   * @return lat
  **/
  @ApiModelProperty(example = "null", value = "Latitude")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }

  public BranchLocatorResponse _long(String _long) {
    this._long = _long;
    return this;
  }

   /**
   * Longitude
   * @return _long
  **/
  @ApiModelProperty(example = "null", value = "Longitude")
  public String getLong() {
    return _long;
  }

  public void setLong(String _long) {
    this._long = _long;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchLocatorResponse branchLocatorResponse = (BranchLocatorResponse) o;
    return Objects.equals(this.name, branchLocatorResponse.name) &&
        Objects.equals(this.id, branchLocatorResponse.id) &&
        Objects.equals(this.lat, branchLocatorResponse.lat) &&
        Objects.equals(this._long, branchLocatorResponse._long);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, lat, _long);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchLocatorResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    _long: ").append(toIndentedString(_long)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

