/**
 * BranchLocatorAPI
 * Branch API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: contact@hsbc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BranchLocatorReq
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-15T11:18:16.803Z")
public class BranchLocatorReq   {
  @SerializedName("Lat")
  private String lat = null;

  @SerializedName("Long")
  private String _long = null;

  @SerializedName("rad")
  private String rad = null;

  public BranchLocatorReq lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Latitude
   * @return lat
  **/
  @ApiModelProperty(example = "null", value = "Latitude")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }

  public BranchLocatorReq _long(String _long) {
    this._long = _long;
    return this;
  }

   /**
   * Longitude
   * @return _long
  **/
  @ApiModelProperty(example = "null", value = "Longitude")
  public String getLong() {
    return _long;
  }

  public void setLong(String _long) {
    this._long = _long;
  }

  public BranchLocatorReq rad(String rad) {
    this.rad = rad;
    return this;
  }

   /**
   * Radius
   * @return rad
  **/
  @ApiModelProperty(example = "null", value = "Radius")
  public String getRad() {
    return rad;
  }

  public void setRad(String rad) {
    this.rad = rad;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchLocatorReq branchLocatorReq = (BranchLocatorReq) o;
    return Objects.equals(this.lat, branchLocatorReq.lat) &&
        Objects.equals(this._long, branchLocatorReq._long) &&
        Objects.equals(this.rad, branchLocatorReq.rad);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, _long, rad);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BranchLocatorReq {\n");
    
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    _long: ").append(toIndentedString(_long)).append("\n");
    sb.append("    rad: ").append(toIndentedString(rad)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

